# Generated by Django 4.1.7 on 2023-03-15 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meeet_app', '0002_alter_venue_address_alter_venue_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meet',
            name='director',
        ),
        migrations.AddField(
            model_name='meet',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
